ALTER TABLE users
ADD COLUMN IF NOT EXISTS public_info JSONB DEFAULT '{}'::jsonb NOT NULL,
ADD COLUMN IF NOT EXISTS friends_info JSONB DEFAULT '{}'::jsonb NOT NULL,
ADD COLUMN IF NOT EXISTS private_info JSONB DEFAULT '{}'::jsonb NOT NULL,
ADD COLUMN IF NOT EXISTS music_preferences JSONB DEFAULT '{}'::jsonb NOT NULL;